<?
$arUrlRewrite = array(
	array(
		"CONDITION" => "#^/online/([\\.\\-0-9a-zA-Z]+)(/?)([^/]*)#",
		"RULE" => "alias=\$1",
		"ID" => "bitrix:im.router",
		"PATH" => "/desktop_app/router.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/news/.*.*.*.*.*.*.*.*.*.*.*.*.*.*#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/bitrix/services/ymarket/#",
		"RULE" => "",
		"ID" => "",
		"PATH" => "/bitrix/services/ymarket/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/latest_product/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/latest_product/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/news_product/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/news_product/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/online/(/?)([^/]*)#",
		"RULE" => "",
		"ID" => "bitrix:im.router",
		"PATH" => "/desktop_app/router.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/personal/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/personal/order/#",
		"RULE" => "",
		"ID" => "bitrix:sale.personal.order",
		"PATH" => "/personal/order/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/new-products/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/new-products/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/content/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/content/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/catalog/#",
		"RULE" => "",
		"ID" => "bitrix:catalog",
		"PATH" => "/catalog/filter/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/brands/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/brands/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/promo/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/promo/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^\\??(.*)#",
		"RULE" => "&\$1",
		"ID" => "bitrix:catalog.top",
		"PATH" => "/local/templates/amatagroup_index/header.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^\\??(.*)#",
		"RULE" => "&\$1",
		"ID" => "bitrix:catalog.section",
		"PATH" => "/local/templates/amatagroup_index/header.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/store/#",
		"RULE" => "",
		"ID" => "bitrix:catalog.store",
		"PATH" => "/store/index.php",
		"SORT" => "100",
	),
	array(
		"CONDITION" => "#^/news/#",
		"RULE" => "",
		"ID" => "bitrix:news",
		"PATH" => "/news/index.php",
		"SORT" => "100",
	),
);
?>